#
# install-sdk/action.yml
#
# Copyright 2021 Jens A. Koch.
# SPDX-License-Identifier: BSL-1.0
# This file is part of hikogui.
#

name: "Install Vulkan SDK"
description: "Installs the current Vulkan SDK"
inputs:
  VULKAN_VERSION:
    description: "Version number of the vulkan sdk"
    required: true
  VULKAN_SDK:
    description: "Location of the vulkan sdk"
    required: true

runs:
  using: "composite"
  steps:
    - name: Download Vulkan SDK
      env:
        VULKAN_SDK_URL: https://sdk.lunarg.com/sdk/download/${{inputs.VULKAN_VERSION}}/windows/VulkanSDK-${{inputs.VULKAN_VERSION}}-Installer.exe?Human=true
      shell: pwsh
      run: curl -L --silent --show-error --output VulkanSDK.exe "${{env.VULKAN_SDK_URL}}"

    - name: Install Vulkan SDK
      shell: cmd
      run: VulkanSDK.exe in com.lunarg.vulkan.core com.lunarg.vulkan.vma --accept-licenses --default-answer --confirm-command --root ${{inputs.VULKAN_SDK}}
         
    - name: Download Vulkan runtime
      env:
        VULKAN_RUN_URL: https://sdk.lunarg.com/sdk/download/${{inputs.VULKAN_VERSION}}/windows/vulkan-runtime-components.zip?Human=true
      shell: pwsh
      run: curl -L --silent --show-error --output vulkan-runtime.zip "${{env.VULKAN_RUN_URL}}"

    - name: Install Vulkan Runtime (vulkan-1.dll)
      shell: pwsh
      run: 7z e vulkan-runtime.zip -o"${{inputs.VULKAN_SDK}}\runtime\x64" */x64

    - name: Reduce VULKAN_SDK size before caching
      shell: pwsh
      working-directory: ${{inputs.VULKAN_SDK}}
      run: |
        "Folder size before: {0:N2} MB" -f ((ls . -r | Measure-Object -Property Length -Sum).Sum / 1MB)
        Remove-Item -Recurse -Force "Demos"
        Remove-Item -Recurse -Force "Helpers"
        Remove-Item -Recurse -Force "installerResources"
        Remove-Item -Recurse -Force "Licenses"
        Remove-Item -Recurse -Force "Templates"
        Remove-Item -Recurse -Force "Source"
        Remove-Item .\maintenancetool.*, .\components.xml, .\network.xml, .\installer.dat, .\InstallationLog.txt
        "Folder size after: {0:N2} MB" -f ((ls . -r | Measure-Object -Property Length -Sum).Sum / 1MB)

